const missions = [
    'Win a ranked game with another player in ANY game.',
    'Convince another player to sing part of a song.',
    'Get another player to say your full name outloud.',
    'Convince another player to play Minecraft with you.',
    'Lose a game to another player (Not this one!)',
    'Get another player to give you a compliment.',
    'Convince another player to do an impression of you.',
    'Convince another player to restart Discord.',
    'Get another player to join a separate voice channel with you.',
    'Make up a word and get another player to ask you what it means.',
    'Get another player with a bofa/ligma/sugma type set-up.',
    'Convince another player it\'s time to change their avatar.',
    'Get the whole call to mute their mics.',
    'Make another player share a random fact from their life.',
    'Get another player to send you a picture of themself.',
    'Find out what another player\'s underwear color is.',
    'Convince another player to get pizza for their next meal.',
    'Get 3 people to react to a discord message.',
    'Tell a joke and get another player to laugh.',
    'Get another player to fact check you.',
    'Get another player to say a number above 10 trillion.',
    'Get another player to say a negative number.',
    'Convince people you\'ve taken up a new obscure hobby.',
    'Use a made-up idiom, have no one suspect it\s fake.',
    'Get another player to finish your sentence.',
    'Get another player to explain a game to you.',
    'Get another player to make an animal sound.',
    'Convince another player to say their full name.',
    'Get another player\'s birthday wrong. Get them to correct you.',
    'Convince another player to do an impression of someone else in the call.',
    'Get another player to say "Bless You" three times.',
    'Get another player to tell you what they ate today.',
    'Get another player to cure your hiccups.',
    'Get another player to repeat themselves three times.',
    'Get another player to say "I love you."',
    'Convince another player to whistle.',
    'Get another player to remind you of something. If they do, check off this mission.',
    'Get another player to say something in a different language.'
  ];
  
  export default missions;